version: '3.7'

services:
  worker:
    build: .
    init: true
    environment:
      - NODE_ENV=production
    networks:
      zennet:
  nginx:
    build: load-balancer
    volumes:
      - lb-data:/etc/nginx/
    container_name: images-cat-fe-lb
    ports:
      - 8030:8000
    networks:
      zennet:
    depends_on:
      - worker
volumes:
  lb-data:
    name: 'images-cat-fe-lb-volume'
networks:
  zennet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
          gateway: 192.168.90.1
